// BountyScope — evidence signatures (TRUE POSITIVE ONLY design, ported from
// ReconSpider Pro v10). Every pattern is a concrete server-error / data-leakage
// indicator; generic strings are excluded. Baseline comparison eliminates FPs.
'use strict';

const BS_DETECT = {

  SQLi_ERROR: [
    /SQL syntax.*MySQL/i,
    /Warning.*mysql_/i,
    /MySQLSyntaxErrorException/i,
    /valid MySQL result/i,
    /check the manual that (?:corresponds to|right syntax)/i,
    /You have an error in your SQL syntax/i,
    /mysql_fetch_array\(\) expects parameter/i,
    /mysql_num_rows\(\) expects parameter/i,
    /supplied argument is not a valid MySQL result/i,
    /ORA-\d{4,5}/,
    /Oracle.*Driver/i,
    /quoted string not properly terminated/i,
    /ORA-01756/,
    /ora-00933/i,
    /Microsoft OLE DB Provider for SQL Server/i,
    /Unclosed quotation mark after the character string/i,
    /Microsoft SQL Native Client error/i,
    /ODBC SQL Server Driver/i,
    /SQLServer JDBC Driver/i,
    /com\.microsoft\.sqlserver/i,
    /Incorrect syntax near/i,
    /Unclosed quotation mark/i,
    /SqlException/i,
    /PostgreSQL.*ERROR/i,
    /pg_query\(\):.*failed/i,
    /supplied argument is not a valid PostgreSQL/i,
    /PSQLException/i,
    /ERROR:\s+syntax error at or near/i,
    /SQLite.*error/i,
    /sqlite3\.OperationalError/i,
    /SQLITE_ERROR/i,
    /near ".*": syntax error/i,
    /Data type mismatch in criteria/i,
    /ADODB\.Field error/i,
    /JET Database Engine/i,
    /Access Database Engine/i,
    /Syntax error.*in query/i,
    /Column count doesn't match/i,
    /The used SELECT statements have a different number/i,
    /Unexpected end of command/i,
  ],

  LFI: [
    /root:x:0:0:/,
    /daemon:x:\d+:\d+:/,
    /nobody:x:\d+:\d+:/,
    /www-data:x:\d+:\d+:/,
    /bin\/bash/,
    /bin\/sh/,
    /root:\$[0-9a-zA-Z$./]+:/,
    /\[boot loader\]/i,
    /\[operating systems\]/i,
    /for 16-bit app support/i,
    /\[extensions\]/i,
    /\[fonts\]/i,
    /HTTP_USER_AGENT=/,
    /DOCUMENT_ROOT=/,
    /SERVER_SOFTWARE=/,
    /Warning.*include\(/i,
    /Warning.*require\(/i,
    /failed to open stream: No such file/i,
    /open_basedir restriction in effect/i,
    /^[A-Za-z0-9+\/=]{100,}$/m,
  ],

  RFI: [
    /root:x:0:0:/,
    /www-data:x:\d+:\d+:/,
    /\[boot loader\]/i,
    /\[operating systems\]/i,
  ],

  RCE_CMD: [
    /uid=\d+\([^)]+\)\s+gid=\d+\([^)]+\)/,
    /root:x:0:0:/,
    /www-data:x:\d+:\d+:/,
    /\bwww-data\b.*\$/,
    /command not found/i,
    /sh:\s+\d+:/,
    /bash:\s+[^:]+:\s+command not found/i,
    /\/bin\/bash/,
    /^(?:root|www-data|apache|nginx|nobody|daemon|http|web)\s*$/m,
    /touch: cannot touch/i,
    /\/tmp\/foo/,
  ],

  SSTI: [
    /\b77\b/,
    /\b49\b/,
    /<class 'type'>/,
    /\[object Object\]/,
    /Jinja2/i,
    /TemplateNotFound/i,
    /jinja2\.exceptions/i,
    /freemarker\.core/i,
    /org\.springframework\.expression/i,
    /velocity.*template/i,
    /PebbleException/i,
    /ThymeleafException/i,
    /io\.pebbletemplates/i,
  ],

  SSRF: [
    /ami-id/i,
    /instance-id/i,
    /local-hostname/i,
    /iam\/security-credentials/i,
    /AccessKeyId/i,
    /SecretAccessKey/i,
    /computeMetadata/i,
    /serviceAccounts/i,
    /Connection to (?:127|10|192\.168|172\.(?:1[6-9]|2\d|3[01]))/i,
    /SSH-2\.0/,
    /\+OK/,
    /220.*(?:SMTP|FTP|ssh)/i,
    /dial tcp.*connection refused/i,
    /no route to host/i,
  ],

  OPEN_REDIRECT: [
    /evil\.com/i,
  ],

  XXE: [
    /root:x:0:0:/,
    /\[boot loader\]/i,
    /ami-id/i,
    /instance-id/i,
    /org\.xml\.sax/i,
    /javax\.xml\.parsers/i,
    /external entity/i,
    /SYSTEM.*file:\/\//i,
  ],

  XSS_REFLECT: [
    /<script>alert\(/i,
    /onerror=alert\(/i,
    /onload=alert\(/i,
    /javascript:alert\(/i,
    /<svg\s+onload/i,
    /<img\s+src=x\s+onerror/i,
    /<details\s+open\s+ontoggle/i,
    /eval\(atob\(/i,
    /onerror=prompt\(/i,
  ],
};

// OS_CMD findings share the RCE evidence signatures (uid= output, command errors…)
BS_DETECT.OS_CMD = BS_DETECT.RCE_CMD;
